-- AlterTable
ALTER TABLE "Area" ALTER COLUMN "bare_soil" DROP NOT NULL,
ALTER COLUMN "flood" DROP NOT NULL,
ALTER COLUMN "grass_shrubs" DROP NOT NULL,
ALTER COLUMN "low_vegetation" DROP NOT NULL,
ALTER COLUMN "other_paved" DROP NOT NULL,
ALTER COLUMN "park" DROP NOT NULL,
ALTER COLUMN "public" DROP NOT NULL,
ALTER COLUMN "roads_railroads" DROP NOT NULL,
ALTER COLUMN "school" DROP NOT NULL;
