DROP TABLE IF EXISTS tesa_blockgroup;
CREATE TABLE tesa_blockgroup (
    id VARCHAR NOT NULL UNIQUE,
    geom geometry(MultiPolygon, 4326) NOT NULL,
    "location" VARCHAR NOT NULL DEFAULT 'NATIONAL',
    equity_index FLOAT NOT NULL,
    tree_canopy_gap_max FLOAT NOT NULL,
    water FLOAT NOT NULL,
    tree_canopy FLOAT NOT NULL,
    potential_tree_canopy FLOAT NOT NULL,
    impervious_surface FLOAT NOT NULL,
    area FLOAT NOT NULL,
    poverty_percent FLOAT NOT NULL,
    poverty_percent_normalized FLOAT NOT NULL,
    incorporated_place_mean_tree_equity_score FLOAT,
    poc_percent FLOAT NOT NULL,
    poc_percent_normalized FLOAT NOT NULL,
    unemployment_rate FLOAT NOT NULL,
    unemployment_rate_normalized FLOAT NOT NULL,
    dependent_ratio FLOAT NOT NULL,
    dependent_ratio_normalized FLOAT NOT NULL,
    child_percent FLOAT NOT NULL,
    senior_percent FLOAT NOT NULL,
    tree_equity_score FLOAT NOT NULL,
    congressional_district VARCHAR NOT NULL,
    health_normalized FLOAT NOT NULL,
    total_population FLOAT NOT NULL,
    tree_canopy_goal FLOAT NOT NULL,
    tree_canopy_gap FLOAT NOT NULL,
    temperature FLOAT NOT NULL,
    temperature_normalized FLOAT NOT NULL,
    linguistic_isolation FLOAT NOT NULL,
    linguistic_isolation_normalized FLOAT NOT NULL,
    af_id VARCHAR,
    municipality_slug VARCHAR,
    "state" VARCHAR,
    potential_vegetation FLOAT,
    potential_paved FLOAT,
    unsuitable_surface FLOAT,
    incorporated_place_name VARCHAR,
    mental_health FLOAT,
    ua_name VARCHAR,
    county VARCHAR,
    county_slug VARCHAR,
    afternoon_air_average_temperature FLOAT,
    evening_air_average_temperature FLOAT,
    neighborhood VARCHAR,
    name_ej_criteria VARCHAR,
    number_ej_criteria INT,
    holc_grade VARCHAR,
    subwatershed VARCHAR,
    tree_canopy_gain FLOAT,
    tree_canopy_loss FLOAT,
    health_risk VARCHAR,
    hez BOOLEAN,
    watershed VARCHAR,
    parks_access FLOAT,
    air_pollution VARCHAR,
    qualified_census_tract BOOLEAN,
    light_rail BOOLEAN,
    mean_radiant_temperature_15 FLOAT,
    mean_radiant_temperature_19 FLOAT,
    council_district VARCHAR,
    canopy_change_percent FLOAT,
    ej_disadvantaged VARCHAR,
    asthma_percent FLOAT,
    population_density FLOAT,
    neighborhood_id VARCHAR,
    neighborhood_score INT,
    neighborhood_score_category VARCHAR,
    neighborhood_designation VARCHAR,
    ward VARCHAR,
    fips VARCHAR,
    tree_planting_investment_index FLOAT,
    social_vulnerability_index FLOAT,
    road_emissions FLOAT,
    municipality_name VARCHAR,
    low_food_access BOOLEAN,
    community_garden BOOLEAN,
    affordable_housing BOOLEAN,
    ttf_tree_equity_planting VARCHAR,
    ej_screen FLOAT
);

CREATE INDEX tmp_tesa_blockgroup_idx ON tesa_blockgroup USING gist (geom);

DROP TABLE IF EXISTS tesa_parcel;
CREATE TABLE tesa_parcel (
    af_id VARCHAR NOT NULL UNIQUE,
    geoid VARCHAR NOT NULL,
    "location" VARCHAR NOT NULL,
    "address" VARCHAR,
    land_area FLOAT,
    water FLOAT,
    tree_canop FLOAT,
    potential FLOAT,
    impervious FLOAT NOT NULL,
    school BOOLEAN,
    park BOOLEAN,
    public BOOLEAN,
    flood VARCHAR,
    rented BOOLEAN,
    industrial BOOLEAN,
    sidewalk BOOLEAN,
    parking BOOLEAN,
    neighborho VARCHAR,
    open_space BOOLEAN,
    hez BOOLEAN,
    watershed VARCHAR,
    canopygain FLOAT,
    canopyloss FLOAT,
    subwatersh VARCHAR,
    worship BOOLEAN,
    curre_comm BOOLEAN,
    futur_comm BOOLEAN,
    land_use VARCHAR,
    coolcenter VARCHAR,
    qct BOOLEAN,
    busstop BOOLEAN,
    light_rail BOOLEAN,
    mrt_1500 FLOAT,
    mrt_1900 FLOAT,
    vegetation FLOAT,
    paved FLOAT,
    unsuitable FLOAT,
    sv_index FLOAT,
    nhood_type VARCHAR,
    cnpy_chng FLOAT,
    future_lu VARCHAR,
    pub_type VARCHAR,
    brownfield BOOLEAN,
    library BOOLEAN,
    af_housing BOOLEAN,
    comm_gardn BOOLEAN,
    ej_screen FLOAT,
    geom geometry(MultiPolygon, 4326) NOT NULL
);

-- Create index for geometry
CREATE INDEX tmp_tesa_parcel_idx ON tesa_parcel USING gist (geom);

DROP TABLE IF EXISTS tesa_row;
CREATE TABLE tesa_row (
    af_id VARCHAR NOT NULL UNIQUE,
    geoid VARCHAR NOT NULL,
    "location" VARCHAR NOT NULL,
    "address" VARCHAR,
    land_area FLOAT,
    water FLOAT,
    tree_canop FLOAT,
    potential FLOAT,
    impervious FLOAT NOT NULL,
    school BOOLEAN,
    park BOOLEAN,
    public BOOLEAN,
    flood VARCHAR,
    rented BOOLEAN,
    industrial BOOLEAN,
    sidewalk BOOLEAN,
    parking BOOLEAN,
    neighborho VARCHAR,
    open_space BOOLEAN,
    hez BOOLEAN,
    watershed VARCHAR,
    canopygain FLOAT,
    canopyloss FLOAT,
    subwatersh VARCHAR,
    worship BOOLEAN,
    curre_comm BOOLEAN,
    futu_comm BOOLEAN,
    land_use VARCHAR,
    coolcenter VARCHAR,
    qct BOOLEAN,
    busstop BOOLEAN,
    light_rail BOOLEAN,
    mrt_1500 FLOAT,
    mrt_1900 FLOAT,
    vegetation FLOAT,
    paved FLOAT,
    unsuitable FLOAT,
    sv_index FLOAT,
    nhood_type VARCHAR,
    cnpy_chng FLOAT,
    future_lu VARCHAR,
    pub_type VARCHAR,
    brownfield BOOLEAN,
    library BOOLEAN,
    af_housing BOOLEAN,
    comm_gardn BOOLEAN,
    ej_screen FLOAT,
    geom geometry(MultiPolygon, 4326) NOT NULL
);

-- Create index for geometry
CREATE INDEX tmp_tesa_row_idx ON tesa_row USING gist (geom);


