-- AlterTable
ALTER TABLE "Blockgroup" ADD COLUMN     "building_shade12" DOUBLE PRECISION,
ADD COLUMN     "building_shade15" DOUBLE PRECISION,
ADD COLUMN     "building_shade18" DOUBLE PRECISION,
ADD COLUMN     "total_shade12" DOUBLE PRECISION,
ADD COLUMN     "total_shade15" DOUBLE PRECISION,
ADD COLUMN     "total_shade18" DOUBLE PRECISION,
ADD COLUMN     "trees_shade12" DOUBLE PRECISION,
ADD COLUMN     "trees_shade15" DOUBLE PRECISION,
ADD COLUMN     "trees_shade18" DOUBLE PRECISION,
ALTER COLUMN "area_sqkm" DROP NOT NULL;
